// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_mgsub
std::string rcpp_mgsub(std::string string, std::vector<std::string> match, std::vector<std::string> replace, bool ic);
RcppExport SEXP _mgsubcpp_rcpp_mgsub(SEXP stringSEXP, SEXP matchSEXP, SEXP replaceSEXP, SEXP icSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type string(stringSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type match(matchSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type replace(replaceSEXP);
    Rcpp::traits::input_parameter< bool >::type ic(icSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mgsub(string, match, replace, ic));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mgsubcpp_rcpp_mgsub", (DL_FUNC) &_mgsubcpp_rcpp_mgsub, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mgsubcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
